import type { BirthProfile, Celebrity, Expert, Panchang, Report, ToolSummary } from '@vedanova/contracts';
export const experts: Expert[] = [
{id:'anaya',name:'Anaya Rao',role:'Vedic guide',specialty:'Vedic',signature:'Divisional charts & life timing',years:18,languages:['English','Hindi'],rating:4.96,reviews:2840,rate:24,online:true,avatar:'/assets/expert-anaya.svg',tags:['D1–D10','Dashas','Career']},
{id:'dev',name:'Dev Mehta',role:'KP specialist',specialty:'KP',signature:'Sub-lord event timing',years:14,languages:['English','Hindi','Gujarati'],rating:4.91,reviews:1920,rate:22,online:true,avatar:'/assets/expert-dev.svg',tags:['KP','Questions','Timing']},
{id:'meera',name:'Meera Iyer',role:'Nadi reader',specialty:'Nadi',signature:'Bhrigu Nandi patterns',years:26,languages:['English','Tamil'],rating:4.94,reviews:3184,rate:29,online:false,avatar:'/assets/expert-meera.svg',tags:['Nadi','Karma','Relationships']},
{id:'kavya',name:'Kavya Sen',role:'Tarot & intuition',specialty:'Tarot',signature:'Decision clarity readings',years:11,languages:['English','Hindi','Bengali'],rating:4.89,reviews:1442,rate:18,online:true,avatar:'/assets/expert-kavya.svg',tags:['Tarot','Love','Choices']},
{id:'arjun',name:'Arjun Bhat',role:'Numerology guide',specialty:'Numerology',signature:'Name, timing & Lo Shu',years:16,languages:['English','Hindi'],rating:4.87,reviews:1336,rate:17,online:true,avatar:'/assets/expert-arjun.svg',tags:['Names','Lo Shu','Business']},
{id:'isha',name:'Isha Kulkarni',role:'Vastu consultant',specialty:'Vastu',signature:'Home & workspace alignment',years:20,languages:['English','Hindi','Marathi'],rating:4.93,reviews:2219,rate:31,online:false,avatar:'/assets/expert-isha.svg',tags:['Vastu','Home','Business']}];
export const tools: ToolSummary[] = [
{id:'kundli',title:'Birth Chart',eyebrow:'D1 · Core',description:'A clean Vedic chart snapshot with planetary placements and current dasha.',category:'Core chart',path:'/tools/kundli'},
{id:'dasha',title:'Dasha Timeline',eyebrow:'Vimshottari',description:'Explore the major and sub-periods shaping your current chapter.',category:'Timing',path:'/tools/dasha'},
{id:'compatibility',title:'Compatibility',eyebrow:'Ashta-koota',description:'Compare two birth profiles with an explainable demo score.',category:'Relationships',path:'/tools/compatibility'},
{id:'numerology',title:'Numerology',eyebrow:'Numbers',description:'Life path, expression, soul urge and personal-year snapshot.',category:'Purpose',path:'/tools/numerology'},
{id:'past-life',title:'Past Life · D60',eyebrow:'Shashtiamsa',description:'A narrative-style D60 demo with clarity about birth-time sensitivity.',category:'Purpose',path:'/tools/past-life',premium:true},
{id:'astro-gps',title:'Astro GPS',eyebrow:'Location',description:'Rank demo destinations for wealth, love, peace, fame or spirituality.',category:'Research',path:'/tools/astro-gps',premium:true},
{id:'celebrities',title:'Celebrity Charts',eyebrow:'Research',description:'Study public life milestones through a curated demo chart catalogue.',category:'Research',path:'/celebrities'},
{id:'muhurat',title:'Muhurat Finder',eyebrow:'Timing',description:'Demo entry point for future electional-astrology calculations.',category:'Timing',path:'/tools'},
{id:'navamsa',title:'Navamsa · D9',eyebrow:'Relationships',description:'Foundation for a future D9 marital and dharma analysis.',category:'Relationships',path:'/tools'},
{id:'yogas',title:'Raja Yogas',eyebrow:'Patterns',description:'Future deterministic yoga detection behind the same API layer.',category:'Core chart',path:'/tools'}];
export const profile: BirthProfile={name:'Demo Seeker',date:'1993-11-18',time:'07:42',place:'Mumbai, India',timezone:'Asia/Kolkata'};
export const panchang:Panchang={location:'Mumbai, India',dateLabel:'Monday · 7 September 2026',tithi:'Krishna Dwadashi',nakshatra:'Pushya',yoga:'Siddhi',rahuKaal:'07:47–09:20',moonSign:'Cancer',sunrise:'06:24',sunset:'18:47',note:'A quieter day for consolidation, review and finishing work already in motion.'};
export const celebrities:Celebrity[]=[{id:'jobs',name:'Steve Jobs',field:'Technology',rating:'AA',milestone:'Apple turnaround era',dasha:'Mercury · Venus',pattern:'Communication, aesthetics and product focus become the public signature.'},{id:'oprah',name:'Oprah Winfrey',field:'Media',rating:'AA',milestone:'National syndication breakthrough',dasha:'Venus · Jupiter',pattern:'Audience growth aligns with benefic visibility and network expansion.'},{id:'ambani',name:'Dhirubhai Ambani',field:'Business',rating:'AA',milestone:'Reliance public expansion',dasha:'Rahu · Mercury',pattern:'Scale, markets and communications dominate the growth narrative.'},{id:'viv',name:'Swami Vivekananda',field:'Spirituality',rating:'A',milestone:'Chicago Parliament of Religions',dasha:'Mercury · Jupiter',pattern:'Teaching and cross-cultural transmission activate at once.'},{id:'chaplin',name:'Charlie Chaplin',field:'Film',rating:'AA',milestone:'Global silent-film fame',dasha:'Venus · Mercury',pattern:'Artistry and expressive skill combine into mass recognition.'},{id:'elizabeth',name:'Queen Elizabeth II',field:'Royalty',rating:'AA',milestone:'Accession to the throne',dasha:'Saturn · Mercury',pattern:'Duty, institution and formal responsibility define the period.'}];
export const reports:Report[]=[{id:'twenty-year',title:'20-Year Life Arc',description:'A long-form roadmap covering major dasha chapters, opportunities and reflective prompts.',price:899,pages:'40+ pages',badge:'Most complete'},{id:'relationships',title:'Relationship Blueprint',description:'D1/D9-inspired relationship themes, communication patterns and timing windows.',price:499,pages:'18+ pages',badge:'Popular'},{id:'career',title:'Career Compass',description:'Career themes, strengths, decision prompts and a five-year demo timeline.',price:599,pages:'22+ pages',badge:'New'}];
