import { ArrowRight,CheckCircle2,Clock3,CreditCard,IndianRupee,MessageCircle,Save,ShieldCheck,Sparkles,Star,UserRound,WalletCards } from 'lucide-react';
import { useEffect,useState } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import type { BirthProfile,Wallet } from '@vedanova/contracts';
import { BirthForm,demoProfile } from '../components/BirthForm';
import { ChartGlyph } from '../components/ChartGlyph';
import { PageState } from '../components/PageState';
import { api } from '../lib/api';
import { useAsync } from '../lib/useAsync';

export function DashboardPage(){const{data,loading,error}=useAsync(api.dashboard,[]);return <section className="section page-top"><div className="container"><div className="dashboard-head"><div><div className="eyebrow">My space</div><h1>Everything useful, one level deep.</h1><p>Your birth profile, consultations, recent tools and purchased-report demos.</p></div><Link className="button" to="/tools"><Sparkles/> Open tools</Link></div><PageState loading={loading} error={error}>{data&&<><div className="dashboard-metrics"><Link className="card dash-metric" to="/wallet"><WalletCards/><span>Wallet</span><strong>₹{data.wallet.balance}</strong><small>Demo balance</small></Link><Link className="card dash-metric" to="/consultations"><MessageCircle/><span>Consultations</span><strong>{data.consultations.length}</strong><small>Recent + scheduled</small></Link><Link className="card dash-metric" to="/reports"><CreditCard/><span>Reports</span><strong>{data.reports.length}</strong><small>Available products</small></Link><Link className="card dash-metric" to="/tools"><Sparkles/><span>Recent tools</span><strong>{data.recentTools.length}</strong><small>Continue exploring</small></Link></div><div className="dashboard-layout"><div className="card dash-chart"><ChartGlyph/><div><div className="eyebrow">Primary birth profile</div><h2>{data.profile.name}</h2><p>{data.profile.date} · {data.profile.time} · {data.profile.place}</p><div className="hero-actions"><Link className="button" to="/tools/kundli">Open chart</Link><Link className="button button-ghost" to="/account">Edit profile</Link></div></div></div><div className="card insight-panel"><div className="eyebrow">Saved insights</div>{data.savedInsights.map(x=><div className="saved-insight" key={x.title}><b>{x.title}</b><p>{x.body}</p></div>)}</div></div><div className="dashboard-columns"><div className="card content-card"><div className="section-mini-head"><div><div className="eyebrow">Recent tools</div><h3>Continue where you left off</h3></div><Link to="/tools">All tools</Link></div>{data.recentTools.map(x=><Link className="list-row" to={`/tools/${x.toolId}`} key={x.toolId}><span><b>{x.title}</b><small>{x.when}</small></span><ArrowRight size={16}/></Link>)}</div><div className="card content-card"><div className="section-mini-head"><div><div className="eyebrow">Consultations</div><h3>Recent & upcoming</h3></div><Link to="/consultations">History</Link></div>{data.consultations.map(x=><div className="list-row static" key={x.id}><span><b>{x.expertName}</b><small>{x.topic} · {x.startedAt}</small></span><span className={`status-pill ${x.status}`}>{x.status}</span></div>)}</div></div></>}</PageState></div></section>}

export function AccountPage(){const{data,loading,error,setData}=useAsync(api.profile,[]);const[profile,setProfile]=useState<BirthProfile>(demoProfile);const[saved,setSaved]=useState(false);const[busy,setBusy]=useState(false);useEffect(()=>{if(data)setProfile(data)},[data]);const save=async()=>{setBusy(true);setSaved(false);try{const next=await api.saveProfile(profile);setData(next);setSaved(true)}finally{setBusy(false)}};return <section className="section page-top"><div className="container narrow-wide"><div className="page-hero compact-hero"><div className="eyebrow">Birth profile</div><h1>Enter once. Reuse everywhere.</h1><p>In production this becomes the canonical input source for every deterministic chart calculation.</p></div><PageState loading={loading} error={error}><div className="card account-card"><div className="account-card-head"><UserRound/><div><h2>Primary profile</h2><p>Demo data is prefilled so every module works immediately.</p></div></div><BirthForm value={profile} onChange={setProfile}/><button className="button button-large" onClick={()=>void save()} disabled={busy}><Save/> {busy?'Saving…':'Save demo profile'}</button>{saved&&<div className="success-inline"><CheckCircle2/> Saved through PATCH /api/profile</div>}</div></PageState></div></section>}

export function ConsultationsPage(){const{data:consultationData,loading,error}=useAsync(api.consultations,[]);const data=consultationData??[];return <section className="section page-top"><div className="container"><div className="page-hero compact-hero"><div className="eyebrow">Consultation history</div><h1>Every conversation has a clear state.</h1><p>Completed, active and scheduled demo sessions are modeled separately.</p></div><PageState loading={loading} error={error}><div className="consultation-list">{data.map(x=><article className="card consultation-card" key={x.id}><div className="consult-icon"><MessageCircle/></div><div><div className="eyebrow">{x.specialty} · {x.id}</div><h3>{x.expertName}</h3><p>{x.topic}</p><div className="consult-meta"><span><Clock3/> {x.startedAt}</span><span>{x.minutes} min</span><span>₹{x.amount}</span></div></div><div className="consult-actions"><span className={`status-pill ${x.status}`}>{x.status}</span><Link className="button button-ghost" to={`/experts/${x.expertId}`}>Open expert</Link></div></article>)}</div></PageState></div></section>}

export function WalletPage(){const{data,loading,error}=useAsync(api.wallet,[]);const[wallet,setWallet]=useState<Wallet|null>(null);const[amount,setAmount]=useState(1000);const[busy,setBusy]=useState(false);const current=wallet||data;const topUp=async()=>{setBusy(true);try{setWallet(await api.topUp(amount))}finally{setBusy(false)}};return <section className="section page-top"><div className="container narrow-wide"><div className="page-hero compact-hero"><div className="eyebrow">Demo wallet</div><h1>Billing flow without real billing.</h1><p>The API returns a new demo balance and transaction. No gateway or money movement is connected.</p></div><PageState loading={loading} error={error}>{current&&<><div className="wallet-hero card"><div><span>Available demo balance</span><strong>₹{current.balance.toLocaleString()}</strong><small>Includes ₹{current.welcomeCredits} welcome credit</small></div><WalletCards/></div><div className="wallet-grid"><div className="card topup-card"><div className="eyebrow">Top up</div><h2>Add demo credits</h2><div className="amount-pills">{[500,1000,1500,2500].map(x=><button key={x} className={amount===x?'active':''} onClick={()=>setAmount(x)}>₹{x}</button>)}</div><label><span>Custom amount</span><div className="money-input"><IndianRupee/><input type="number" min="100" max="10000" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></div></label><button className="button button-large" disabled={busy} onClick={()=>void topUp()}>{busy?'Adding…':'Add demo credits'}</button><div className="secure-line"><ShieldCheck/> No payment method requested</div></div><div className="card content-card"><div className="eyebrow">Transactions</div><div className="transaction-list">{current.transactions.map(x=><div className="transaction-row" key={x.id}><span><b>{x.label}</b><small>{x.date}</small></span><strong className={x.amount>=0?'credit':'debit'}>{x.amount>=0?'+':''}₹{Math.abs(x.amount)}</strong></div>)}</div></div></div></>}</PageState></div></section>}

export function ExpertPortalPage(){const{data,loading,error}=useAsync(api.portal,[]);const[form,setForm]=useState({name:'',specialty:'Vedic',experience:'10',languages:'English, Hindi'});const[done,setDone]=useState<string|null>(null);const[busy,setBusy]=useState(false);const apply=async()=>{setBusy(true);try{const r=await api.applyExpert(form);setDone(r.applicationId)}finally{setBusy(false)}};return <section className="section page-top"><div className="container"><div className="page-hero compact-hero"><div className="eyebrow">Astrologer portal</div><h1>Onboarding and operating dashboard, in one demo.</h1><p>Existing practitioners see stats; new applicants can submit a server-backed demo application.</p></div><PageState loading={loading} error={error}>{data&&<><div className="portal-metrics"><div className="card"><span>Today</span><strong>₹{data.todayEarnings}</strong><small>demo earnings</small></div><div className="card"><span>This month</span><strong>₹{data.monthEarnings.toLocaleString()}</strong><small>demo earnings</small></div><div className="card"><span>Active chats</span><strong>{data.activeChats}</strong><small>{data.responseTime} response</small></div><div className="card"><span>Rating</span><strong>{data.rating}</strong><small><Star size={12}/> demo quality</small></div></div><div className="portal-grid"><div className="card content-card"><div className="eyebrow">Upcoming</div><h2>Today’s queue</h2>{data.upcoming.map(x=><div className="list-row static" key={x.time}><span><b>{x.time} · {x.client}</b><small>{x.topic}</small></span><span className="status-pill scheduled">scheduled</span></div>)}</div><div className="card booking-form"><div className="eyebrow">Join the network</div><h2>Demo application</h2><label><span>Name</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Specialty</span><select value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})}>{['Vedic','Nadi','KP','Tarot','Numerology','Palmistry','Vastu'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Years of experience</span><input type="number" value={form.experience} onChange={e=>setForm({...form,experience:e.target.value})}/></label><label><span>Languages</span><input value={form.languages} onChange={e=>setForm({...form,languages:e.target.value})}/></label><button className="button button-large" onClick={()=>void apply()} disabled={busy||!form.name}>{busy?'Submitting…':'Submit demo application'}</button>{done&&<div className="success-inline"><CheckCircle2/> Application {done} created</div>}</div></div></>}</PageState></div></section>}

export function SignInPage(){const navigate=useNavigate();return <section className="section page-top auth-page"><div className="card auth-card"><div className="auth-mark"><img src="/assets/logo-mark.svg" alt=""/></div><div className="eyebrow">Demo account</div><h1>Welcome to VedaNova.</h1><p>Authentication is intentionally not connected yet. Continue with the seeded demo profile to inspect every account flow.</p><button className="button button-large" onClick={()=>navigate('/dashboard')}><UserRound/> Continue as Demo Seeker</button><div className="secure-line"><ShieldCheck/> No OAuth token is requested or stored</div></div></section>}
