import { ArrowLeft,ArrowRight,BookOpen,CheckCircle2,PackageCheck,ShieldCheck,Sparkles,Video } from 'lucide-react';
import { useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import type { Order } from '@vedanova/contracts';
import { PageState } from '../components/PageState';
import { api } from '../lib/api';
import { useAsync } from '../lib/useAsync';

function PurchaseSuccess({order,message}:{order:Order;message:string}){return <div className="purchase-success card"><CheckCircle2/><div><div className="eyebrow">Demo order complete</div><h3>{order.title}</h3><p>{message}</p><span className="tag">{order.id}</span></div></div>}

export function ReportsPage(){const{data:reportData,loading,error}=useAsync(api.reports,[]);const data=reportData??[];return <section className="section page-top"><div className="container"><div className="page-hero compact-hero"><div className="eyebrow">Long-form reports</div><h1>Go deeper without turning the interface into a wall of text.</h1><p>Each report has a full detail and demo-checkout flow.</p></div><PageState loading={loading} error={error}><div className="report-grid">{data.map(x=><article className="card report-card" key={x.id}><div className="report-badge">{x.badge}</div><h2>{x.title}</h2><p>{x.description}</p><ul className="clean-list compact-list">{x.includes.slice(0,3).map(i=><li key={i}>{i}</li>)}</ul><div className="report-price"><strong>₹{x.price}</strong><span>{x.pages}</span></div><Link className="button" to={`/reports/${x.id}`}>View report <ArrowRight size={15}/></Link></article>)}</div></PageState></div></section>}

export function ReportDetailPage(){const{id=''}=useParams();const{data:r,loading,error}=useAsync(()=>api.report(id),[id]);const[purchasing,setPurchasing]=useState(false);const[done,setDone]=useState<{order:Order;message:string}|null>(null);const buy=async()=>{setPurchasing(true);try{setDone(await api.buyReport(id))}finally{setPurchasing(false)}};return <section className="section page-top"><div className="container narrow-wide"><PageState loading={loading} error={error}>{r&&<><Link className="back-link" to="/reports"><ArrowLeft size={15}/> Reports</Link><div className="commerce-detail"><div><div className="eyebrow">{r.badge} · {r.pages}</div><h1>{r.title}</h1><p className="lead">{r.description}</p><div className="included-grid">{r.includes.map(x=><div className="included-item" key={x}><CheckCircle2/>{x}</div>)}</div></div><aside className="card checkout-card"><span>Demo price</span><strong>₹{r.price}</strong><p>{r.delivery}</p><button className="button button-large" onClick={()=>void buy()} disabled={purchasing}>{purchasing?'Creating demo order…':'Preview checkout'}</button><div className="secure-line"><ShieldCheck/> No payment processor connected</div></aside></div>{done&&<PurchaseSuccess {...done}/>}<div className="report-preview card"><div className="eyebrow">Preview</div><div className="preview-cover"><Sparkles/><span>VEDANOVA · PERSONAL REPORT</span><h2>{r.title}</h2><small>Demo Seeker · static preview</small></div><div className="preview-pages"><div><span>01</span><b>Chart profile</b><p>Key placements and a concise context map.</p></div><div><span>02</span><b>Timing chapters</b><p>Major cycles presented as themes and decisions.</p></div><div><span>03</span><b>Action prompts</b><p>Questions to take into real planning or consultation.</p></div></div></div></>}</PageState></div></section>}

export function StorePage(){const{data:productData,loading,error}=useAsync(api.products,[]);const data=productData??[];return <section className="section page-top"><div className="container"><div className="page-hero compact-hero"><div className="eyebrow">VedaNova Store · demo</div><h1>A complete storefront flow, without pretending the products are live.</h1><p>Static catalog, product detail and safe demo checkout. No shipment or payment occurs.</p></div><PageState loading={loading} error={error}><div className="product-grid">{data.map(x=><Link className="card product-card" to={`/store/${x.id}`} key={x.id}><div className="product-image"><img src={x.image} alt={x.title}/>{x.badge&&<span>{x.badge}</span>}</div><div className="product-copy"><div className="eyebrow">{x.category}</div><h2>{x.title}</h2><p>{x.description}</p><strong>₹{x.price.toLocaleString()}</strong></div></Link>)}</div></PageState></div></section>}

export function ProductDetailPage(){const{id=''}=useParams();const{data:p,loading,error}=useAsync(()=>api.product(id),[id]);const[purchasing,setPurchasing]=useState(false);const[done,setDone]=useState<{order:Order;message:string}|null>(null);const buy=async()=>{setPurchasing(true);try{setDone(await api.buyProduct(id))}finally{setPurchasing(false)}};return <section className="section page-top"><div className="container narrow-wide"><PageState loading={loading} error={error}>{p&&<><Link className="back-link" to="/store"><ArrowLeft size={15}/> Store</Link><div className="product-detail"><div className="card product-detail-image"><img src={p.image} alt={p.title}/></div><div><div className="eyebrow">{p.category} · demo inventory</div><h1>{p.title}</h1><p className="lead-small">{p.description}</p><ul className="check-list">{p.details.map(x=><li key={x}>{x}</li>)}</ul><div className="big-price">₹{p.price.toLocaleString()}</div><button className="button button-large" onClick={()=>void buy()} disabled={purchasing}><PackageCheck/> {purchasing?'Creating demo order…':'Demo checkout'}</button><p className="fine-print">No product will be charged, reserved or shipped from this demo.</p></div></div>{done&&<PurchaseSuccess {...done}/>}</>}</PageState></div></section>}

function ServicePage({kind}:{kind:'reading'|'course'}){const[form,setForm]=useState({name:'Demo Seeker',email:'demo@example.com',note:''});const[done,setDone]=useState<string|null>(null);const[busy,setBusy]=useState(false);const isCourse=kind==='course';const submit=async()=>{setBusy(true);try{const r=await api.bookService(kind,form);setDone(r.message)}finally{setBusy(false)}};return <section className="section page-top"><div className="container narrow-wide"><div className="service-hero card"><div className="service-icon">{isCourse?<BookOpen/>:<Video/>}</div><div><div className="eyebrow">{isCourse?'Learning program':'Private consultation'}</div><h1>{isCourse?'Vedic Astrology Learning Lab':'60-minute Private Reading'}</h1><p className="lead-small">{isCourse?'A demo course-booking page with modules, delivery and enrollment flow.':'A complete booking surface for a future live Zoom/Meet consultation.'}</p></div></div><div className="service-grid"><div className="card content-card"><h2>{isCourse?'What the demo course includes':'What a production reading can include'}</h2><ul className="check-list">{(isCourse?['10 structured video modules','Downloadable study notes','One doubt-clearing session','Research-library access']:['Pre-read of your birth profile','60-minute video consultation','Written recap placeholders','Follow-up resource links']).map(x=><li key={x}>{x}</li>)}</ul><div className="service-price"><span>Demo price</span><strong>{isCourse?'₹24,000':'USD $120'}</strong></div></div><div className="card booking-form"><div className="eyebrow">Request a slot</div><label><span>Name</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Email</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span>{isCourse?'What do you want to learn?':'What do you want to discuss?'}</span><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="button button-large" onClick={()=>void submit()} disabled={busy}>{busy?'Submitting…':isCourse?'Demo enrollment':'Demo booking'}</button>{done&&<div className="success-inline"><CheckCircle2/>{done}</div>}</div></div></div></section>}
export function ReadingPage(){return <ServicePage kind="reading"/>}
export function CoursePage(){return <ServicePage kind="course"/>}
