import { ArrowLeft,BadgeCheck,CalendarClock,Clock3,Languages,MessageCircle,Send,ShieldCheck,Star,WalletCards } from 'lucide-react';
import { useEffect,useRef,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import type { ChatMessage,Expert } from '@vedanova/contracts';
import { ExpertCard } from '../components/ExpertCard';
import { PageState } from '../components/PageState';
import { api } from '../lib/api';
import { useAsync } from '../lib/useAsync';

export function ExpertDetailPage(){const{id=''}=useParams();const{data:e,loading,error}=useAsync(()=>api.expert(id),[id]);const{data:all}=useAsync(()=>api.experts(),[]);return <section className="section page-top"><div className="container"><PageState loading={loading} error={error}>{e&&<><Link className="back-link" to="/experts"><ArrowLeft size={15}/> All experts</Link><div className="expert-profile card"><div className="expert-profile-main"><div className="profile-avatar-wrap"><img src={e.avatar} alt={e.name}/><span className={e.online?'presence online':'presence'}/></div><div><div className="eyebrow">{e.specialty} · {e.verified?'Verified demo profile':'Demo profile'}</div><div className="profile-title"><h1>{e.name}</h1>{e.verified&&<BadgeCheck/>}</div><p className="lead-small">{e.signature}</p><div className="profile-facts"><span><Star/> {e.rating} · {e.reviews.toLocaleString()} reviews</span><span><Clock3/> {e.years} years</span><span><Languages/> {e.languages.join(' · ')}</span></div></div></div><aside className="profile-booking"><div><small>Rate</small><strong>₹{e.rate}<span>/min</span></strong></div><div><small>Availability</small><b>{e.nextAvailable}</b></div><Link className="button button-large" to={`/chat/${e.id}`}><MessageCircle/> Start demo chat</Link><button className="button button-ghost"><CalendarClock/> Schedule preview</button></aside></div><div className="profile-grid"><section className="card content-card"><div className="eyebrow">About</div><h2>A method you can understand.</h2><p>{e.bio}</p><h3>Methods</h3><div className="tag-row">{e.methods.map(x=><span className="tag" key={x}>{x}</span>)}</div><h3>Good questions for this guide</h3><ul className="clean-list"><li>What is the most important theme in my current timing cycle?</li><li>What decision factors am I underweighting?</li><li>Where does the chart show repetition rather than a one-off event?</li></ul></section><aside className="card trust-card"><ShieldCheck/><h3>Demo consultation guardrails</h3><p>No real astrologer is contacted and no payment occurs. Production can attach identity verification, scheduling, moderation and billing to this route.</p></aside></div>{all&&<section className="related-section"><div className="section-head"><div><div className="eyebrow">You might also consider</div><h2>Other methods, same question.</h2></div></div><div className="card-grid expert-grid">{all.filter(x=>x.id!==e.id).slice(0,4).map(x=><ExpertCard key={x.id} expert={x}/>)}</div></section>}</>}</PageState></div></section>}

export function ChatPage(){
  const{expertId='anaya'}=useParams();const[e,setE]=useState<Expert|null>(null);const[session,setSession]=useState('');const[msg,setMsg]=useState('');const[log,setLog]=useState<ChatMessage[]>([]);const[prompts,setPrompts]=useState<string[]>([]);const[wallet,setWallet]=useState(0);const[seconds,setSeconds]=useState(0);const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);const[error,setError]=useState<string|null>(null);const bottomRef=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{let alive=true;setLoading(true);api.createChat(expertId).then(s=>{if(!alive)return;setE(s.expert);setSession(s.sessionId);setWallet(s.walletBalance);setPrompts(s.suggestedPrompts);setLog([{id:'welcome',role:'assistant',createdAt:new Date().toISOString(),content:`Namaste — I’m ${s.expert.name.split(' ')[0]} in this demo. Ask a specific question and I’ll show how the production conversation flow will work.`}])}).catch(err=>{if(alive)setError(err instanceof Error?err.message:'Could not start chat')}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[expertId]);
  useEffect(()=>{const timer=window.setInterval(()=>setSeconds(x=>x+1),1000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>bottomRef.current?.scrollIntoView({behavior:'smooth'}),[log]);
  const send=async(text=msg)=>{if(!text.trim()||!session||sending)return;setMsg('');setSending(true);setLog(x=>[...x,{id:`u-${Date.now()}`,role:'user',createdAt:new Date().toISOString(),content:text}]);try{const r=await api.sendMessage(session,text,expertId);setLog(x=>[...x,r])}catch(err){setError(err instanceof Error?err.message:'Message failed')}finally{setSending(false)}};
  const mm=String(Math.floor(seconds/60)).padStart(2,'0'),ss=String(seconds%60).padStart(2,'0');
  return <section className="section page-top chat-page"><div className="container"><PageState loading={loading} error={error&&!e?error:null}>{e&&<><div className="chat-topline"><Link className="back-link" to={`/experts/${e.id}`}><ArrowLeft size={15}/> {e.name}</Link><div className="chat-session-meta"><span><Clock3/> {mm}:{ss}</span><Link to="/wallet"><WalletCards/> ₹{wallet}</Link><span className="demo-live">Demo session</span></div></div><div className="chat-shell"><aside className="card chat-sidebar"><div className="chat-expert"><img className="chat-avatar" src={e.avatar} alt={e.name}/><span className={e.online?'presence online':'presence'}/><h2>{e.name}</h2><p>{e.signature}</p></div><div className="chat-side-section"><b>Methods</b><div className="tag-row">{e.methods.map(x=><span className="tag" key={x}>{x}</span>)}</div></div><div className="chat-side-section"><b>Suggested questions</b>{prompts.map(p=><button className="prompt-button" key={p} onClick={()=>void send(p)}>{p}</button>)}</div><div className="demo-note">First 3 minutes are represented as free in this demo. No billing is active.</div></aside><div className="card chat-main"><div className="messages"><div className="chat-date">Today · demo conversation</div>{log.map(m=><div className={`message ${m.role}`} key={m.id}><div>{m.content}</div><small>{new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>)}{sending&&<div className="message assistant"><div className="typing"><i/><i/><i/></div></div>}<div ref={bottomRef}/></div>{error&&e&&<div className="inline-error">{error}</div>}<div className="chat-composer"><textarea value={msg} onChange={x=>setMsg(x.target.value)} onKeyDown={x=>{if(x.key==='Enter'&&!x.shiftKey){x.preventDefault();void send()}}} placeholder="Ask about career, relationships, money or timing…"/><button className="button send-button" onClick={()=>void send()} disabled={sending||!msg.trim()}><Send size={17}/><span>Send</span></button></div></div></div></>}</PageState></div></section>}
