import { ArrowRight,CheckCircle2,MessageCircle,ShieldCheck,Sparkles,Star,WandSparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ExpertCard } from '../components/ExpertCard';
import { PageState } from '../components/PageState';
import { ToolCard } from '../components/ToolCard';
import { api } from '../lib/api';
import { useAsync } from '../lib/useAsync';

const practices=[['Vedic','D1, D9, dashas & classical Jyotish'],['Nadi','Planet chains & life patterns'],['KP','Focused questions & timing'],['Tarot','Reflective guidance for decisions'],['Numerology','Names, cycles & Lo Shu'],['Vastu','Home and workspace alignment']];
const faq=[
  ['Is this already a real astrology calculation engine?','Not yet. The current backend is an explicit static demo. Every screen and API contract is production-shaped, but astronomical values will be replaced by a deterministic calculation service later.'],
  ['Are the chat experts real people?','The profiles in this demo are original fictional product data. The consultation flow is implemented so real onboarding, availability and billing can be connected later.'],
  ['Does the demo charge money?','No. Wallet top-ups and checkouts return demo orders only. No payment processor is connected.'],
  ['Why keep everything behind an API if the data is static?','So the frontend never has to be rewritten when the real astrology engine, database, payments and AI services are connected.']
];

export function HomePage(){
  const{data,loading,error}=useAsync(api.home,[]);
  return <>
    <section className="hero section"><div className="container hero-grid"><div className="hero-copy"><div className="kicker"><Sparkles size={16}/> Astrology interfaces built for clarity</div><h1>Know the pattern.<br/><em>Choose the next move.</em></h1><p className="lead">Talk to a guide, explore 30+ Vedic research modules, compare timing cycles and keep the useful parts in one calm workspace.</p><div className="hero-actions"><Link className="button button-large" to="/experts"><MessageCircle size={18}/> Start a consultation</Link><Link className="button button-large button-ghost" to="/tools">Explore all tools <ArrowRight size={18}/></Link></div><div className="trust-row"><span><ShieldCheck size={16}/> Explainable demo flows</span><span><Star size={16}/> Original expert profiles</span><span><WandSparkles size={16}/> API-first architecture</span></div></div><div className="hero-visual"><img className="orbit-art" src="/assets/hero-orbit.svg" alt="Abstract planetary orbit illustration"/><div className="floating-card fc-a"><span className="orb-symbol">☉</span><div><small>Current focus</small><b>Jupiter · Mercury</b></div></div><div className="floating-card fc-b"><span className="orb-symbol">✦</span><div><small>Daily signal</small><b>Pushya · Siddhi</b></div></div><div className="floating-card fc-c"><span className="orb-symbol">⌁</span><div><small>Tool library</small><b>30+ modules</b></div></div></div></div></section>
    <section className="metrics-strip"><div className="container metrics-grid"><div><strong>30+</strong><span>interactive modules</span></div><div><strong>1</strong><span>shared birth profile</span></div><div><strong>100%</strong><span>API-driven demo</span></div><div><strong>24/7</strong><span>demo AI fallback</span></div></div></section>
    <PageState loading={loading} error={error}>{data&&<>
      <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Guides online</div><h2>Start with a person, not a maze.</h2><p>Browse by method, language, availability and rate.</p></div><Link to="/experts" className="text-link">View all experts <ArrowRight size={16}/></Link></div><div className="card-grid expert-grid">{data.experts.map(e=><ExpertCard key={e.id} expert={e}/>)}</div></div></section>
      <section className="section section-tint"><div className="container"><div className="section-head"><div><div className="eyebrow">Practices</div><h2>Choose the lens that fits the question.</h2></div></div><div className="practice-grid">{practices.map(([name,copy])=><Link className="practice-card card" to={`/experts?specialty=${encodeURIComponent(name)}`} key={name}><span className="practice-icon">{name.slice(0,1)}</span><div><h3>{name}</h3><p>{copy}</p></div><ArrowRight size={18}/></Link>)}</div></div></section>
      <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Chart lab</div><h2>Powerful tools, grouped by the question.</h2><p>Every module is a working demo page backed by an API endpoint.</p></div><Link to="/tools" className="text-link">Open tool library <ArrowRight size={16}/></Link></div><div className="card-grid tools-grid">{data.tools.map(t=><ToolCard key={t.id} tool={t}/>)}</div></div></section>
      <section className="section section-tint"><div className="container"><div className="split-head"><div><div className="eyebrow">Daily brief</div><h2>{data.panchang.tithi} · {data.panchang.nakshatra}</h2><p>{data.panchang.note}</p><div className="tag-row"><span className="tag">Moon · {data.panchang.moonSign}</span><span className="tag">Yoga · {data.panchang.yoga}</span><span className="tag">Rahu · {data.panchang.rahuKaal}</span></div><Link className="button button-ghost" to="/daily">Open today’s brief</Link></div><img className="moon-panel" src="/assets/daily-moon.svg" alt="Moon illustration"/></div></div></section>
      <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Stories</div><h2>Designed for useful conversations.</h2></div></div><div className="testimonial-grid">{data.testimonials.map(x=><blockquote className="card quote-card" key={x.name}><div className="quote-mark">“</div><p>{x.quote}</p><footer><b>{x.name}</b><span>{x.city} · with {x.readBy}</span></footer></blockquote>)}</div></div></section>
      <section className="section section-tint"><div className="container"><div className="section-head"><div><div className="eyebrow">How it works</div><h2>One profile, many ways to explore.</h2></div></div><div className="steps-grid">{[['01','Create your profile','Enter birth details once and reuse them across the entire product.'],['02','Choose a tool or expert','Use search, category filters or your dashboard recommendations.'],['03','Keep the useful result','Save the insight, continue to consultation or open a related report.']].map(([n,t,b])=><div className="step-card" key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p></div>)}</div></div></section>
      <section className="section"><div className="container faq-wrap"><div><div className="eyebrow">Product transparency</div><h2>What this demo is—and isn’t.</h2><p>We prefer explicit limitations over pretending static data is a real calculation.</p></div><div className="faq-list">{faq.map(([q,a])=><details className="card faq-item" key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
      <section className="section"><div className="container"><div className="final-cta card"><div><div className="eyebrow">Ready to explore</div><h2>Start with your chart or a conversation.</h2><p>No signup or payment is required in demo mode.</p></div><div className="cta-checks"><span><CheckCircle2/> 30+ modules</span><span><CheckCircle2/> Demo wallet</span><span><CheckCircle2/> Responsive dark mode</span></div><div className="hero-actions"><Link className="button" to="/tools/kundli">Open birth chart</Link><Link className="button button-ghost" to="/experts">Browse experts</Link></div></div></div></section>
    </>}</PageState>
  </>;
}
