import { ArrowLeft,ArrowRight,CalendarDays,Search,Sunrise,Sunset } from 'lucide-react';
import { useMemo,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { ChartGlyph } from '../components/ChartGlyph';
import { EmptyState,PageState } from '../components/PageState';
import { api } from '../lib/api';
import { useAsync } from '../lib/useAsync';

export function DailyPage(){const{data:p,loading,error}=useAsync(api.panchang,[]);return <section className="section page-top"><div className="container narrow-wide"><div className="page-hero compact-hero"><div className="eyebrow">Daily sky</div><h1>Your day, without the doom-scroll.</h1><p>One concise demo brief with calendar context and explicit limits.</p></div><PageState loading={loading} error={error}>{p&&<><div className="card daily-hero"><div><span className="date-chip"><CalendarDays/> {p.dateLabel}</span><h2>{p.tithi} · {p.nakshatra}</h2><p>{p.note}</p><div className="tag-row"><span className="tag">Moon · {p.moonSign}</span><span className="tag">Yoga · {p.yoga}</span><span className="tag">Rahu · {p.rahuKaal}</span></div></div><img src="/assets/daily-moon.svg" alt="Moon illustration"/></div><div className="daily-grid"><div className="card content-card"><div className="eyebrow">Day rhythm</div><div className="sun-grid"><div><Sunrise/><span>Sunrise</span><b>{p.sunrise}</b></div><div><Sunset/><span>Sunset</span><b>{p.sunset}</b></div></div><h3>Good demo uses</h3><ul className="check-list">{p.auspicious.map(x=><li key={x}>{x}</li>)}</ul></div><div className="card content-card"><div className="eyebrow">Keep light</div><h3>Avoid over-optimizing the day.</h3><ul className="clean-list">{p.avoid.map(x=><li key={x}>{x}</li>)}</ul><p className="fine-print">Panchang values on this screen are static demo content until a deterministic location/time service is connected.</p></div></div></>}</PageState></div></section>}

export function CelebritiesPage(){const[q,setQ]=useState('');const[category,setCategory]=useState('All');const{data:celebrityData,loading,error}=useAsync(()=>api.celebrities(q,category),[q,category]);const data=celebrityData??[];const cats=useMemo(()=>['All','Billionaires','Rags to Riches','Spiritual Guides','Royalty','Internet & Culture'],[]);return <section className="section page-top"><div className="container"><div className="page-hero compact-hero"><div className="eyebrow">Chart research</div><h1>Study milestones, not mythology.</h1><p>Original demo research cards model how a curated, source-rated celebrity chart database can work.</p></div><div className="tool-controls card"><label className="search-field wide-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people, fields or tags…"/></label><div className="filter-pills">{cats.map(c=><button key={c} className={c===category?'filter-pill active':'filter-pill'} onClick={()=>setCategory(c)}>{c}</button>)}</div></div><PageState loading={loading} error={error}>{data.length?<div className="celebrity-grid">{data.map(x=><Link className="card celeb-card" to={`/celebrities/${x.id}`} key={x.id}><div className="celeb-top"><span className="rating-pill">{x.rating}</span><span>{x.category}</span></div><h3>{x.name}</h3><p>{x.field}</p><b>{x.milestone}</b><p>{x.pattern}</p><div className="celeb-foot"><span className="tag">{x.dasha}</span><ArrowRight size={16}/></div></Link>)}</div>:<EmptyState title="No research records match" body="Try another category or a broader search."/>}</PageState></div></section>}

export function CelebrityDetailPage(){const{id=''}=useParams();const{data:x,loading,error}=useAsync(()=>api.celebrity(id),[id]);return <section className="section page-top"><div className="container narrow-wide"><PageState loading={loading} error={error}>{x&&<><Link className="back-link" to="/celebrities"><ArrowLeft size={15}/> Celebrity research</Link><div className="research-detail-head"><div><div className="eyebrow">{x.rating} source rating · {x.category}</div><h1>{x.name}</h1><p className="lead">{x.field} · {x.birth} · {x.place}</p><div className="tag-row">{x.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div></div><div className="research-fact card"><small>Breakthrough lens</small><strong>{x.dasha}</strong><span>{x.milestone}</span></div></div><div className="research-charts"><div className="card chart-card"><ChartGlyph title="D1"/><div><b>Lagna · {x.ascendant}</b><p>Visible-life demo layer</p></div></div><div className="card chart-card"><ChartGlyph title="D9"/><div><b>Navamsa · {x.navamsa}</b><p>Dharma / maturity demo layer</p></div></div></div><div className="card content-card prose-card"><div className="eyebrow">Research narrative</div><h2>Why this milestone is in the catalog</h2><p>{x.story}</p><h3>Demo timing pattern</h3><p>{x.pattern}</p><div className="demo-disclaimer">This page uses static illustrative chart metadata. It is not claiming validated astronomical calculation for the person shown.</div></div></>}</PageState></div></section>}

export function BlogPage(){const{data:blogData,loading,error}=useAsync(api.blog,[]);const data=blogData??[];return <section className="section page-top"><div className="container"><div className="page-hero compact-hero"><div className="eyebrow">VedaNova Journal</div><h1>Math-honest notes for curious sky-watchers.</h1><p>Product education, technique and decision frameworks without certainty theater.</p></div><PageState loading={loading} error={error}><div className="blog-grid">{data.map(post=><Link className="card blog-card" to={`/blog/${post.slug}`} key={post.slug}><div className="eyebrow">{post.category}</div><h2>{post.title}</h2><p>{post.excerpt}</p><div className="blog-meta"><span>{post.date}</span><span>{post.readTime}</span><ArrowRight size={16}/></div></Link>)}</div></PageState></div></section>}

export function BlogPostPage(){const{slug=''}=useParams();const{data:post,loading,error}=useAsync(()=>api.post(slug),[slug]);return <section className="section page-top"><div className="container article-wrap"><PageState loading={loading} error={error}>{post&&<><Link className="back-link" to="/blog"><ArrowLeft size={15}/> Journal</Link><header className="article-head"><div className="eyebrow">{post.category}</div><h1>{post.title}</h1><p className="lead">{post.excerpt}</p><div className="blog-meta"><span>{post.date}</span><span>{post.readTime}</span></div></header><article className="article-body card">{post.body.map((p,i)=><p key={i}>{p}</p>)}<hr/><p><b>Demo editorial note:</b> This article is original placeholder copy for the VedaNova front-end and can later be replaced by CMS content.</p></article></>}</PageState></div></section>}
