import { useEffect,useState } from 'react';import type { BirthProfile,KundliResult } from '@vedanova/contracts';import { Link,useParams } from 'react-router-dom';import { api } from '../lib/api';import { BirthForm } from '../components/BirthForm';import { ChartGlyph } from '../components/ChartGlyph';import { ExpertCard } from '../components/ExpertCard';
const empty:BirthProfile={name:'Demo Seeker',date:'1993-11-18',time:'07:42',place:'Mumbai, India',timezone:'Asia/Kolkata'};
export function KundliPage(){const[p,setP]=useState(empty);const[r,setR]=useState<KundliResult|null>(null);useEffect(()=>{api.profile().then(setP)},[]);return <section className="section page-top"><div className="container narrow-wide"><div className="eyebrow">D1 · Birth chart</div><h1>Kundli, reduced to what matters.</h1><div className="card input-card"><BirthForm value={p} onChange={setP} compact/></div><button className="button" onClick={async()=>setR(await api.kundli(p))}>Calculate demo chart</button>{r&&<div className="result-grid"><div className="card"><ChartGlyph/></div><div className="card result-copy"><h2>{r.ascendant} rising</h2><p>Moon in {r.moonSign} · {r.nakshatra}</p><p>Current period: {r.activeDasha}</p>{r.strengths.map(s=><span className="tag" key={s}>{s}</span>)}</div></div>}</div></section>}
export function ExpertDetailPage(){const{id=''}=useParams();const[e,setE]=useState<any>(null);useEffect(()=>{api.expert(id).then(setE)},[id]);return <section className="section page-top"><div className="container narrow-wide">{e&&<><ExpertCard expert={e}/><p className="lead-small">This profile is ready for real presence, billing, scheduling and methodology metadata.</p></>}</div></section>}
export function DailyPage(){const[p,setP]=useState<any>(null);useEffect(()=>{api.panchang().then(setP)},[]);return <section className="section page-top"><div className="container narrow-wide"><div className="eyebrow">Daily sky</div><h1>Your day, without the doom-scroll.</h1>{p&&<div className="card daily-hero"><div><span>{p.dateLabel}</span><h2>{p.tithi} · {p.nakshatra}</h2><p>{p.note}</p><div className="tag-row"><span className="tag">Moon · {p.moonSign}</span><span className="tag">Yoga · {p.yoga}</span><span className="tag">Rahu · {p.rahuKaal}</span></div></div><img src="/assets/daily-moon.svg"/></div>}</div></section>}
export function CelebritiesPage(){const[d,setD]=useState<any[]>([]);useEffect(()=>{api.celebrities().then(setD)},[]);return <section className="section page-top"><div className="container"><div className="eyebrow">Chart research</div><h1>Study milestones, not mythology.</h1><div className="celebrity-grid">{d.map(x=><article className="card celeb-card" key={x.id}><div className="eyebrow">{x.rating} source · {x.field}</div><h3>{x.name}</h3><b>{x.milestone}</b><p>{x.pattern}</p><span className="tag">{x.dasha}</span></article>)}</div></div></section>}
export function ReportsPage(){const[d,setD]=useState<any[]>([]);useEffect(()=>{api.reports().then(setD)},[]);return <section className="section page-top"><div className="container"><div className="eyebrow">Premium reports</div><h1>Long-form insight, designed as a product.</h1><div className="report-grid">{d.map(x=><article className="card report-card" key={x.id}><div className="eyebrow">{x.badge}</div><h2>{x.title}</h2><p>{x.description}</p><strong>₹{x.price}</strong><button className="button">Preview checkout</button></article>)}</div></div></section>}
export function DashboardPage(){return <section className="section page-top"><div className="container"><div className="eyebrow">My space</div><h1>Your chart, conversations and reports in one place.</h1><div className="dashboard-grid"><div className="card dash-chart"><ChartGlyph/><div><h2>Demo Seeker</h2><p>18 Nov 1993 · 07:42 · Mumbai</p><Link className="button" to="/tools/kundli">Open chart</Link></div></div></div></div></section>}
export function GenericToolPage(){const{id}=useParams();return <section className="section page-top"><div className="container narrow-wide"><div className="eyebrow">Modular tool</div><h1>{id?.replaceAll('-',' ')}</h1><p className="lead">This route is wired into the modular tool library. Its real calculation can replace the server stub without changing navigation or design.</p><Link className="button" to="/tools">Back to tools</Link></div></section>}
export function ChatPage(){const{expertId='anaya'}=useParams();const[e,setE]=useState<any>(null);const[msg,setMsg]=useState('');const[log,setLog]=useState<any[]>([]);useEffect(()=>{api.createChat(expertId).then(s=>{setE(s.expert);setLog([{role:'assistant',content:`Namaste — I’m ${s.expert.name.split(' ')[0]}. What would you like to explore?`}])})},[expertId]);const send=async()=>{if(!msg.trim())return;const text=msg;setMsg('');setLog(x=>[...x,{role:'user',content:text}]);const r=await api.sendMessage(`demo-${expertId}`,text,expertId);setLog(x=>[...x,r])};return <section className="section page-top"><div className="container chat-shell"><aside className="card chat-sidebar">{e&&<><img className="chat-avatar" src={e.avatar}/><h2>{e.name}</h2><p>{e.signature}</p></>}</aside><div className="card chat-main"><div className="messages">{log.map((m,i)=><div className={`message ${m.role}`} key={i}><div>{m.content}</div></div>)}</div><div className="chat-composer"><textarea value={msg} onChange={x=>setMsg(x.target.value)} placeholder="Ask about career, love, money or timing…"/><button className="button" onClick={send}>Send</button></div></div></div></section>}
