import { AlertTriangle,ArrowLeft,CheckCircle2,Clock3,LockKeyhole,MapPinned,Sparkles } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import type { BirthProfile,ToolRunResult,ToolSummary } from '@vedanova/contracts';
import { BirthForm,demoProfile } from '../components/BirthForm';
import { ChartGlyph } from '../components/ChartGlyph';
import { PageState } from '../components/PageState';
import { api } from '../lib/api';

const goals=['Money','Love','Peace','Fame','Spirituality'];
const activities=['Launch a project','Sign a contract','Buy a home','Start a job','Health routine','Buy gold','Family ceremony'];
const years=['2026','2027','2028','2029','2030'];

function ScoreRing({value,max,label}:{value:number;max:number;label:string}){const pct=Math.round(value/max*100);return <div className="score-wrap"><div className="score-ring" style={{'--score':`${pct*3.6}deg`} as React.CSSProperties}><div><strong>{value}</strong><span>/ {max}</span></div></div><b>{label}</b></div>}

function ToolInputs({tool,profile,setProfile,profileB,setProfileB,name,setName,date,setDate,goal,setGoal,year,setYear,activity,setActivity,lagna,setLagna}:{tool:ToolSummary;profile:BirthProfile;setProfile:(p:BirthProfile)=>void;profileB:BirthProfile;setProfileB:(p:BirthProfile)=>void;name:string;setName:(x:string)=>void;date:string;setDate:(x:string)=>void;goal:string;setGoal:(x:string)=>void;year:string;setYear:(x:string)=>void;activity:string;setActivity:(x:string)=>void;lagna:string;setLagna:(x:string)=>void}){
  if(tool.inputKind==='none')return <div className="no-input card"><Sparkles/><div><b>No birth data needed</b><p>This free demo module can run immediately.</p></div></div>;
  if(tool.inputKind==='name-date')return <div className="compact-form-grid"><label><span>Name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Date of birth</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>;
  if(tool.inputKind==='chart-search')return <div className="compact-form-grid"><label><span>Lagna</span><select value={lagna} onChange={e=>setLagna(e.target.value)}>{['Scorpio','Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Sagittarius','Capricorn','Aquarius','Pisces'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Placement filter</span><select><option>Mars · 10th house</option><option>Jupiter · 11th house</option><option>Venus · 2nd house</option><option>Rahu · 1st house</option></select></label></div>;
  const isTwo=tool.inputKind==='two-births'||tool.inputKind==='two-births-year';
  return <div className="workbench-input-stack">
    {tool.inputKind==='birth-goal'&&<div><div className="input-step"><span>01</span><div><b>Choose your goal</b><p>The demo ranking changes its explanatory context around this choice.</p></div></div><div className="choice-grid">{goals.map(x=><button key={x} className={goal===x?'choice-card active':'choice-card'} onClick={()=>setGoal(x)}>{x}</button>)}</div></div>}
    {tool.inputKind==='birth-activity'&&<div className="compact-form-grid"><label><span>Activity</span><select value={activity} onChange={e=>setActivity(e.target.value)}>{activities.map(x=><option key={x}>{x}</option>)}</select></label></div>}
    {(tool.inputKind==='birth-year'||tool.inputKind==='two-births-year')&&<div className="compact-form-grid"><label><span>Year</span><select value={year} onChange={e=>setYear(e.target.value)}>{years.map(x=><option key={x}>{x}</option>)}</select></label></div>}
    <BirthForm value={profile} onChange={setProfile} compact={!isTwo} title={isTwo?'Person A':undefined}/>
    {isTwo&&<BirthForm value={profileB} onChange={setProfileB} title="Person B"/>}
  </div>;
}

function ToolResultView({result}:{result:ToolRunResult}){return <div className="tool-result"><div className="result-intro card"><div><div className="eyebrow">Demo result</div><h2>{result.title}</h2><p className="lead-small">{result.summary}</p></div>{result.score&&<ScoreRing {...result.score}/>}</div>{result.metrics.length>0&&<div className="metric-cards">{result.metrics.map(x=><div className="card metric-card" key={x.label}><span>{x.label}</span><strong>{x.value}</strong>{x.note&&<small>{x.note}</small>}</div>)}</div>}{result.toolId==='kundli'&&<div className="card chart-result-card"><ChartGlyph title="D1"/><div><h3>Chart view</h3><p>The visual is intentionally symbolic in stub mode. Production will map real calculated longitudes and houses.</p></div></div>}{result.timeline&&<div className="card result-block"><div className="eyebrow">Timeline</div><div className="timeline">{result.timeline.map((x,i)=><div className="timeline-item" key={`${x.title}-${i}`}><div className="timeline-rail"><span/></div><div><div className="timeline-head"><b>{x.title}</b><span>{x.start} → {x.end}</span></div><span className="tag">{x.tag}</span><p>{x.note}</p></div></div>)}</div></div>}{result.table&&<div className="card result-block table-block"><div className="eyebrow">Detailed data</div><div className="table-scroll"><table><thead><tr>{result.table.columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{result.table.rows.map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div></div>}<div className="result-sections">{result.sections.map((section,i)=><article className={`card result-section ${section.tone||''}`} key={`${section.title}-${i}`}><div className="result-section-number">{String(i+1).padStart(2,'0')}</div><div><h3>{section.title}</h3><p>{section.body}</p>{section.items&&section.items.length>0&&<ul>{section.items.map(x=><li key={x}><CheckCircle2 size={15}/>{x}</li>)}</ul>}</div></article>)}</div><div className="demo-disclaimer"><AlertTriangle size={16}/><span>{result.disclaimer}</span></div></div>}

export function ToolWorkbenchPage(){
  const{id='kundli'}=useParams();const[tool,setTool]=useState<ToolSummary|null>(null);const[profile,setProfile]=useState<BirthProfile>(demoProfile);const[profileB,setProfileB]=useState<BirthProfile>({...demoProfile,name:'Demo Partner',date:'1995-03-04',time:'13:15',place:'Pune, India'});const[name,setName]=useState('Demo Seeker');const[date,setDate]=useState('1993-11-18');const[goal,setGoal]=useState('Money');const[year,setYear]=useState('2027');const[activity,setActivity]=useState('Launch a project');const[lagna,setLagna]=useState('Scorpio');const[result,setResult]=useState<ToolRunResult|null>(null);const[loading,setLoading]=useState(true);const[running,setRunning]=useState(false);const[error,setError]=useState<string|null>(null);
  useEffect(()=>{let alive=true;setLoading(true);setError(null);setResult(null);Promise.all([api.tool(id),api.profile()]).then(([t,p])=>{if(!alive)return;setTool(t);setProfile(p);setName(p.name);setDate(p.date)}).catch(e=>{if(alive)setError(e instanceof Error?e.message:'Could not load tool')}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[id]);
  const payload=useMemo<Record<string,unknown>>(()=>({profile,personA:profile,personB:profileB,name,date,goal,year,activity,lagna}),[profile,profileB,name,date,goal,year,activity,lagna]);
  const run=async()=>{setRunning(true);setError(null);try{setResult(await api.runTool(id,payload));setTimeout(()=>document.getElementById('tool-result')?.scrollIntoView({behavior:'smooth',block:'start'}),50)}catch(e){setError(e instanceof Error?e.message:'Could not run tool')}finally{setRunning(false)}};
  return <section className="section page-top"><div className="container"><PageState loading={loading} error={error&&!tool?error:null}>{tool&&<><Link className="back-link" to="/tools"><ArrowLeft size={15}/> All tools</Link><div className="tool-hero"><div><div className="eyebrow">{tool.eyebrow} · {tool.category}</div><h1>{tool.title}</h1><p className="lead">{tool.description}</p><div className="tag-row">{tool.highlights.map(x=><span className="tag" key={x}>{x}</span>)}</div></div><div className="tool-status card"><div className={tool.premium?'status-icon premium':'status-icon'}>{tool.premium?<LockKeyhole/>:<Sparkles/>}</div><div><b>{tool.premium?`Premium demo · ₹${tool.price}`:'Free demo'}</b><p>{tool.premium?'Checkout is simulated; no charge occurs.':'Runs instantly against the API stub.'}</p></div></div></div><div className="workbench card"><div className="workbench-head"><div><div className="eyebrow">Input</div><h2>Configure the reading</h2></div><div className="saved-profile"><Clock3 size={14}/> Demo profile loaded</div></div><ToolInputs tool={tool} profile={profile} setProfile={setProfile} profileB={profileB} setProfileB={setProfileB} name={name} setName={setName} date={date} setDate={setDate} goal={goal} setGoal={setGoal} year={year} setYear={setYear} activity={activity} setActivity={setActivity} lagna={lagna} setLagna={setLagna}/><button className="button button-large run-button" onClick={run} disabled={running}>{running?'Calculating demo…':'Generate demo result'} <MapPinned size={17}/></button>{error&&tool&&<div className="inline-error"><AlertTriangle size={15}/>{error}</div>}</div>{result&&<div id="tool-result"><ToolResultView result={result}/></div>}</>}</PageState></div></section>;
}
